### ISSUE TITLE
No remote link returned from get_resource_url function

### ISSUE THREAD

**Issue by RobWDG** [tonyfujs/dkanr#27]
This function isn't working for my version of DKAN (dkan-7.x-1.13.5)
Could the [["field_link_remote_file"]][["und"]][[1]][["uri"]] be added to the request types please?

**Comment by tonyfujs** [comment]
Thanks @RobWDG. Will look into this. Can you share the URL to your DKAN site?

**Comment by RobWDG** [comment]
Yes, sure its https://www.statistics.digitalresources.jisc.ac.uk/

**Comment by seladore** [comment]
@tonyfujs here is [an example](https://www.statistics.digitalresources.jisc.ac.uk/api/dataset/node/2400.json) of a resource with `field_link_remote_file` populated

**Comment by RobWDG** [comment]
@tonyfujs @seladore sorry I should have given an example dataset and resource I was using dataset node 2394 and resource 2395

**Comment by tonyfujs** [comment]
@RobWDG @seladore Just updated the master branch. Fixed now.
