### ISSUE TITLE
Variable declared twice

### ISSUE THREAD

**Issue by seladore** [tonyfujs/dkanr#28]
Just wondering, is there a reason why `token` is declared twice in `dkanr_setup()`?

https://github.com/tonyfujs/dkanr/blob/913805dc8fa183e69ffa8b86a90c3ff26b3c92e8/R/dkanr_settings.R#L69-L76

**Comment by tonyfujs** [comment]
Requesting the token only once was returning invalid tokens, and for some reason, this solved it. I don't understand why it works, but it does... I don't really see any downside leaving it as is. Thoughts?

**Comment by seladore** [comment]
Got it! I don't see a downside either, I was just curious about why it was there. Thanks!
